import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { DailySummary, WaterIntakeEntry, UrineOutputEntry, SugarMonitorEntry } from '@/types';

export function exportToPDF(
  patientName: string,
  selectedDate: string,
  summary: DailySummary | null,
  waterList: WaterIntakeEntry[] = [],
  urineList: UrineOutputEntry[] = [],
  sugarList: SugarMonitorEntry[] = []
): void {
  const doc = new jsPDF();

  const safeWater = Array.isArray(waterList) ? waterList : [];
  const safeUrine = Array.isArray(urineList) ? urineList : [];
  const safeSugar = Array.isArray(sugarList) ? sugarList : [];

  const totalIntake = summary?.total_intake_ml ?? safeWater.reduce((acc, curr) => acc + Number(curr.amount_ml || 0), 0);
  const totalOutput = summary?.total_output_ml ?? safeUrine.reduce((acc, curr) => acc + Number(curr.volume_ml || 0), 0);
  const netBalance = totalIntake - totalOutput;

  // Header Banner
  doc.setFillColor(31, 56, 100);
  doc.rect(0, 0, 210, 25, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`Patient Health Monitor — ${patientName || 'Yousef'}`, 14, 16);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${selectedDate}`, 160, 16);

  let currentY = 32;

  // Daily Summary Header
  doc.setTextColor(31, 56, 100);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Daily Summary Overview', 14, currentY);
  currentY += 4;

  // Summary Table
  autoTable(doc, {
    startY: currentY,
    head: [['Intake (ml)', 'Output (ml)', 'Net Balance (ml)', 'Avg Sugar (mg/dL)', 'Total Insulin (U)', 'Readings']],
    body: [[
      `${totalIntake} ml`,
      `${totalOutput} ml`,
      `${netBalance} ml`,
      summary?.avg_blood_sugar_mgdl ? `${summary.avg_blood_sugar_mgdl} mg/dL` : 'N/A',
      `${summary?.total_insulin_units ?? 0} Units`,
      `${safeSugar.length}`
    ]],
    theme: 'grid',
    headStyles: { fillColor: [31, 56, 100], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { halign: 'center', fontSize: 10 }
  });

  currentY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // Water Intake Section
  doc.text('Water Intake Log', 14, currentY);
  currentY += 4;

  const waterRows = safeWater.length > 0
    ? safeWater.map(w => [w.entry_time, w.liquid_type, `${w.amount_ml} ml`, w.notes || '-'])
    : [['-', 'No entries recorded for this date', '-', '-']];

  autoTable(doc, {
    startY: currentY,
    head: [['Time', 'Liquid Type', 'Amount', 'Notes']],
    body: waterRows,
    theme: 'striped',
    headStyles: { fillColor: [72, 101, 129] },
    styles: { fontSize: 9 }
  });

  currentY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // Urine Output Section
  doc.text('Urine Output Log', 14, currentY);
  currentY += 4;

  const urineRows = safeUrine.length > 0
    ? safeUrine.map(u => [u.entry_time, `${u.volume_ml} ml`, u.notes || '-'])
    : [['-', 'No entries recorded for this date', '-']];

  autoTable(doc, {
    startY: currentY,
    head: [['Time', 'Volume', 'Notes']],
    body: urineRows,
    theme: 'striped',
    headStyles: { fillColor: [72, 101, 129] },
    styles: { fontSize: 9 }
  });

  currentY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // Blood Sugar & Insulin Section
  doc.text('Blood Sugar & Insulin Monitor', 14, currentY);
  currentY += 4;

  const sugarRows = safeSugar.length > 0
    ? safeSugar.map(s => [
        s.entry_time,
        `${s.blood_sugar_mgdl} mg/dL`,
        s.blood_sugar_mgdl >= 70 && s.blood_sugar_mgdl <= 140 ? 'Normal' : (s.blood_sugar_mgdl < 70 ? 'Low' : 'High'),
        s.insulin_type || '-',
        s.insulin_units ? `${s.insulin_units} U` : '-',
        s.notes || '-'
      ])
    : [['-', 'No glucose readings for this date', '-', '-', '-', '-']];

  autoTable(doc, {
    startY: currentY,
    head: [['Time', 'Glucose', 'Status', 'Insulin Type', 'Units', 'Notes']],
    body: sugarRows,
    theme: 'striped',
    headStyles: { fillColor: [72, 101, 129] },
    styles: { fontSize: 9 }
  });

  // Footer Page Number
  const pageCount = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} — Generated by Yousef Patient Monitor`, 14, 285);
  }

  doc.save(`patient_monitoring_${selectedDate}.pdf`);
}

export function exportToCSV(
  selectedDate: string,
  waterList: WaterIntakeEntry[] = [],
  urineList: UrineOutputEntry[] = [],
  sugarList: SugarMonitorEntry[] = []
): void {
  const safeWater = Array.isArray(waterList) ? waterList : [];
  const safeUrine = Array.isArray(urineList) ? urineList : [];
  const safeSugar = Array.isArray(sugarList) ? sugarList : [];

  let csv = `Date: ${selectedDate}\n\n`;

  csv += `--- WATER INTAKE ---\nTime,Liquid Type,Amount (ml),Notes\n`;
  safeWater.forEach(w => {
    csv += `"${w.entry_time}","${w.liquid_type}",${w.amount_ml},"${w.notes || ''}"\n`;
  });

  csv += `\n--- URINE OUTPUT ---\nTime,Volume (ml),Notes\n`;
  safeUrine.forEach(u => {
    csv += `"${u.entry_time}",${u.volume_ml},"${u.notes || ''}"\n`;
  });

  csv += `\n--- BLOOD SUGAR & INSULIN ---\nTime,Blood Sugar (mg/dL),Insulin Type,Insulin Units,Notes\n`;
  safeSugar.forEach(s => {
    csv += `"${s.entry_time}",${s.blood_sugar_mgdl},"${s.insulin_type || ''}",${s.insulin_units || ''},"${s.notes || ''}"\n`;
  });

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `patient_data_${selectedDate}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
